services:
  - type: web
    name: CS145_IoT_BantayBike_Server
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python test_server.py
    envVars:
      - key: EMQX_BROKER
        sync: false
      - key: EMQX_PORT
        value: 8883
      - key: EMQX_DATA_TOPIC
        value: esp32/data
      - key: EMQX_COMMAND_TOPIC
        value: esp32/command
      - key: EMQX_USERNAME
        sync: false
      - key: EMQX_PASSWORD
        sync: false
      - key: EMQX_CA_CERT
        value: emqxsl-ca.crt
      - key: PORT
        value: 8080